name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
(...)
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   - name: Login to Docker Hub
        
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push the Docker image
           docker build -t sivabalan30/nodejs 
        with:
          push: true
          tags: |
